language: python
python:
  - "3.4"
cache: pip
before_install:
  - pip install "pytest>=2.9" pytest-cov pytest-flake8
#install:
#  - pip install -r requirements.txt
#services:
#  - mysql
script:
  - py.test --flake8