env:
  global:
    - CC_TEST_REPORTER_ID=b75aa588efe2080cf10e1c10a37e554a8b06f65fb08535dba1613ed725f7e424
language: python
python:
  - "3.4"
cache: pip
before_install:
  - pip install "pytest>=2.9" pytest-cov
#  - pip install coverage
#  - pip install codeclimate-test-reporter
#  - pip install pytest-flake8
#  - pip install flake8-codeclimate
#install:
#  - pip install -r requirements.txt
#services:
#  - mysql
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - ./cc-test-reporter before-build
  - py.test --cov=. --cov-report xml
#  - flake8 --exit-zero --format=codeclimate
#  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
