language: python
python:
  - "3.4"
cache: pip
before_install:
  - pip install "pytest>=2.9" pytest-cov
#  - pip install pytest-flake8
#install:
#  - pip install -r requirements.txt
#services:
#  - mysql
script:
  - py.test
after_success:
  - CODECLIMATE_REPO_TOKEN=b75aa588efe2080cf10e1c10a37e554a8b06f65fb08535dba1613ed725f7e424 codeclimate-test-reporter
