name: CI

on: push


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install "pytest>=2.9"
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Run tests
      run: |
        py.test